/** ACP（Agent Client Protocol）协议层 barrel（T8.5a）：纯逻辑，零 Electron / 零 spawn。 */

export {
  type AcpClientHandler,
  type AcpConnection,
  AcpConnectionClosedError,
  type AcpConnectionOptions,
  type AcpDiagnostic,
  AcpHandshakeError,
  AcpRemoteError,
  type AcpRequestOverrides,
  AcpTimeoutError,
  createAcpConnection,
  DEFAULT_ACP_REQUEST_TIMEOUT_MS,
} from "./connection.js";
export {
  ACP_ERROR_AUTH_REQUIRED,
  ACP_ERROR_REQUEST_CANCELLED,
  ACP_ERROR_RESOURCE_NOT_FOUND,
  ACP_JSON_RPC_INTERNAL_ERROR,
  ACP_JSON_RPC_INVALID_PARAMS,
  ACP_JSON_RPC_INVALID_REQUEST,
  ACP_JSON_RPC_METHOD_NOT_FOUND,
  ACP_JSON_RPC_PARSE_ERROR,
  type AcpClassifiedMessage,
  type AcpIncomingNotification,
  type AcpIncomingRequest,
  type AcpIncomingResponse,
  type AcpInvalidMessage,
  type AcpJsonRpcError,
  type AcpJsonRpcId,
  type AcpOutgoingNotification,
  type AcpOutgoingRequest,
  type AcpOutgoingResponse,
  buildAcpError,
  buildAcpNotification,
  buildAcpRequest,
  buildAcpResult,
  classifyAcpLine,
  encodeAcpMessage,
} from "./jsonrpc.js";
export {
  parseContentBlock,
  parseInitializeResult,
  parseLoadSessionResult,
  parseNewSessionResult,
  parsePermissionRequest,
  parsePromptResult,
  parseSessionNotification,
  parseToolCall,
} from "./parse.js";
export {
  ACP_AGENT_METHODS,
  ACP_CLIENT_METHODS,
  ACP_PERMISSION_OPTION_KINDS,
  ACP_PLAN_ENTRY_PRIORITIES,
  ACP_PLAN_ENTRY_STATUSES,
  ACP_PROTOCOL_VERSION,
  ACP_SESSION_UPDATE_TYPES,
  ACP_STOP_REASONS,
  ACP_TOOL_CALL_STATUSES,
  ACP_TOOL_KINDS,
  type AcpClientCapabilities,
  type AcpContentBlockView,
  type AcpImplementationInfo,
  type AcpInitializeOptions,
  type AcpInitializeResult,
  type AcpLoadSessionParams,
  type AcpLoadSessionResult,
  type AcpNewSessionParams,
  type AcpNewSessionResult,
  type AcpOutgoingContentBlock,
  type AcpPermissionDecision,
  type AcpPermissionOptionView,
  type AcpPermissionRequestView,
  type AcpPlanEntryView,
  type AcpPromptParams,
  type AcpPromptResult,
  type AcpSessionNotificationView,
  type AcpSessionUpdateType,
  type AcpSessionUpdateView,
  type AcpStopReason,
  type AcpTextBlock,
  type AcpToolCallContentView,
  type AcpToolCallLocationView,
  type AcpToolCallStatus,
  type AcpToolCallView,
  type AcpToolKind,
  isAcpPermissionOptionKind,
  isAcpSessionUpdateType,
  isAcpStopReason,
  isAcpToolCallStatus,
  isAcpToolKind,
} from "./types.js";
