/** 统一 AgentEvent 类型 + JSONL 流解析（W2.1b）barrel。 */

export {
  createLineDecoder,
  DEFAULT_MAX_LINE_LENGTH,
  type InvalidJsonlLine,
  isJsonObject,
  type JsonlRecord,
  type LineDecoder,
  type LineDecoderOptions,
  nativeEventType,
  type ParsedJsonlLine,
  parseJsonlLine,
  type StreamChunk,
  splitLines,
  toRawEvent,
} from "./jsonl.js";
export { decodeLines, parseJsonlLines, readJsonlStream } from "./stream.js";
export {
  ADAPTER_CAPABILITY_NAMES,
  type AdapterCapabilities,
  type AdapterCapabilityName,
  AGENT_ACTION_STATUSES,
  AGENT_EVENT_KINDS,
  type AgentActionStatus,
  type AgentEvent,
  type AgentEventKind,
  CAPABILITY_SUPPORTS,
  type CapabilitySupport,
  type CommandEvent,
  type EndEvent,
  FILE_CHANGE_KINDS,
  type FileChangeEvent,
  type FileChangeKind,
  isAgentActionStatus,
  isAgentEventKind,
  isCapabilitySupport,
  isFileChangeKind,
  isTextChannel,
  type PermissionRequestEvent,
  type RawEvent,
  type SessionStartEvent,
  TEXT_CHANNELS,
  type TextChannel,
  type TextEvent,
  type TokenUsage,
} from "./types.js";
